options:
  n1kv-vsm-name:
    type: string
    default: "vsm-p"
    description: "N1KV VSM virtual machine (VM) name"
  n1kv-vsm-role:
    type: string
    default: "primary"
    description: "Nexus1000v VSMs role - primary or secondary"
  n1kv-vsm-domain-id:
    type: int
    default: 101
    description: "Domain id this Nexus1000v VSM will control"
  n1kv-vsm-password:
    type: string
    default: "N1k12345"
    description: "Password of the admin user for the VSM VM"
  n1kv-vsm-mgmt-ip:
    type: string
    default: ""
    description: "VSM virtual machine management ip address"
  n1kv-vsm-mgmt-netmask:
    type: string
    default: ""
    description: "VSM virtual machines management netmask"
  n1kv-vsm-mgmt-gateway:
    type: string
    default: ""
    description: "VSM virtual machines management gateway"
  n1kv-vsm-console-pts:
    type: int
    default: 2
    description: "VSM virtual machine console port"
  n1kv-vsm-vm-vcpu:
    type: int
    default: 2
    description: "Number of VCPU for the VSM VM"
  n1kv-vsm-memory-size:
    type: int
    default: 4
    description: "Memory size (in KiB) for the VSM VM"
  n1kv-vsm-disk-size:
    type: int
    default: 4
    description: "Disk size (in GB) for the VSM VM"
  n1kv-bridge-name:
    type: string
    default: "br-int"
    description: "Bridge name behind which the VSM will be attached"
  n1kv-phy-intf-bridge:
    type: string
    default: "eth0"
    description: "Physical uplink interface for the bridge"
  n1kv-vsm-ctrl-interface:
    type: string
    default: "vsm-ctrl0"
    description: "Control tap interface name for the VSM VM"
  n1kv-vsm-ctrl-mac:
    type: string
    default: ""
    description: "Mac address of Control interface from VSM. By default is assigned randomly."
  n1kv-vsm-mgmt-interface:
    type: string
    default: "vsm-mgmt0"
    description: "Management tap interface name for the VSM VM"
  n1kv-vsm-mgmt-mac:
    type: string
    default: ""
    description: "Mac address of Management interface from VSM. By default is assigned randomly."
  n1kv-vsm-pkt-interface:
    type: string
    default: "vsm-pkt0"
    description: "Packet tap interface name for the VSM VM"
  n1kv-vsm-pkt-mac:
    type: string
    default: ""
    description: "Mac address of Packet interface from VSM. By default is assigned randomly."
  n1kv-vsm-vnc-port:
    type: int
    default: 8901
    description: "VNC port number to of the VSM console"
  n1kv-source:
    type: string
    default: distro
    description: "Additinal sources: ppa:myteam/ppa, deb http://my.archive.com/ubuntu main|KEYID"
  n1kv-version:
    type: string
    default: ""
    description: "(Optional) Indicates VSM version. By default picks up the latest"
  n1kv-local-repo:
    type: string
    default: ""
    description: "(Optional) Provide the local address of VSM iso package"


