options:
  n1k-vsm-name:
    type: string
    default: "vsm-p"
    description: "VSM virtual machine name"
  n1k-vsm-role:
    type: string
    default: "primary"
    description: "This VSMs role primary or secondary"
  n1k-vsm-domainid:
    type: int
    default: 101
    description: "Domain id this vsm will be controlling"
  n1k-vsm-password:
    type: string
    default: "N1k12345"
    description: "admin password for the VSM VM"
  n1k-vsm-mgmt-ip:
    type: string
    default: "10.193.180.138"
    description: "VSM VMs management ip address"
  n1k-vsm-mgmt-netmask:
    type: string
    default: "255.255.255.0"
    description: "VSM VMs management netmask"
  n1k-vsm-mgmt-gateway:
    type: string
    default: "10.193.180.254"
    description: "VSM VMs management gateway"
  n1k-vsm-console-pts:
    type: int
    default: 2
    description: "VSM virtual machine name"
  ovsbridge:
    type: string
    default: "br-int"
    description: "ovs bridge behind which the vsm will be attached"
  physicalinterfaceforovs:
    type: string
    default: "eth0"
    description: "physical uplink interface for the ovs bridge"
  isoimage:
    type: string
    default: "n1000v-dk9.5.2.1.SK1.2.1.iso"
    description: "VSM virtual machine name"
  n1k-vsm-ctrl-interface:
    type: string
    default: "tap0"
    description: "Control tap interface name"
  n1k-vsm-ctrlmac:
    type: string
    default: "00:10:11:72:40:00"
    description: "Mac address of Control interface from VSM"
  n1k-vsm-mgmt-interface:
    type: string
    default: "tap1"
    description: "Management tap interface name"
  n1k-vsm-mgmtmac:
    type: string
    default: "00:10:11:72:40:02"
    description: "Management tap interface name"
  n1k-vsm-pktinterface:
    type: string
    default: "tap2"
    description: "Packet tap interface name"
  n1k-vsm-pktmac:
    type: string
    default: "00:10:11:72:40:03"
    description: "Packet tap interface name"
  n1k-vsm-vm-memory:
    type: int
    default: 2048000
    description: "Memory for the VSM VM"
  n1k-vsm-vm-vcpu:
    type: int
    default: 2
    description: "Number of VCPU for the VSM VM"
  n1k-vsm-vm-disksize:
    type: int
    default: 4
    description: "Disk size for the VSM VM"
  n1kv-source: deb https://shivrao:ZSCc3jxB4RMLrLqZlp9T@private-ppa.launchpad.net/springfield-team/n1k-staging/ubuntu precise main,deb-src https://shivrao:ZSCc3jxB4RMLrLqZlp9T@private-ppa.launchpad.net/springfield-team/n1k-staging/ubuntu precise main|F5DB2BA06DB3EEB4
