options:
  n1kv-vsm-name:
    type: string
    default: "vsm-p"
    description: "Nexus1000v VSM virtual machine name"
  n1kv-vsm-role:
    type: string
    default: "primary"
    description: "Nexus1000v VSMs role - primary or secondary"
  n1kv-vsm-domain-id:
    type: int
    default: 101
    description: "Domain id this Nexus1000v VSM will control"
  n1kv-vsm-password:
    type: string
    default: "N1k12345"
    description: "Password of the admin user for the VSM virtual machine"
  n1kv-vsm-mgmt-ip:
    type: string
    default: ""
    description: "VSM virtual machine management ip address"
  n1kv-vsm-mgmt-netmask:
    type: string
    default: ""
    description: "VSM virtual machines management netmask"
  n1kv-vsm-mgmt-gateway:
    type: string
    default: ""
    description: "VSM virtual machines management gateway"
  n1kv-vsm-console-pts:
    type: int
    default: 2
    description: "VSM virtual machine console port"
  n1kv-bridge-name:
    type: string
    default: "br-int"
    description: "Bridge name behind which the VSM will be attached"
  n1kv-phy-intf-bridge:
    type: string
    default: "eth0"
    description: "Physical uplink interface for the bridge"
  n1kv-vsm-ctrl-interface:
    type: string
    default: "tap0"
    description: "Control tap interface name for the VSM VM"
  n1kv-vsm-ctrl-mac:
    type: string
    default: "00:10:11:72:40:00"
    description: "Mac address of Control interface from VSM"
  n1kv-vsm-mgmt-interface:
    type: string
    default: "tap1"
    description: "Management tap interface name for the VSM VM"
  n1kv-vsm-mgmt-mac:
    type: string
    default: "00:10:11:72:40:02"
    description: "Mac address of Management interface from VSM"
  n1kv-vsm-pkt-interface:
    type: string
    default: "tap2"
    description: "Packet tap interface name for the VSM VM"
  n1kv-vsm-pkt-mac:
    type: string
    default: "00:10:11:72:40:03"
    description: "Mac address of Packet interface from VSM"
  n1kv-source:
    type: string
    default: distro
    description: "Additinal sources: ppa:myteam/ppa, deb http://my.archive.com/ubuntu main|KEYID"
  n1kv-version:
    type: string
    default: ""
    description: "(Optional) Indicates VSM version. By default picks up the latest"
  n1kv-local-repo:
    type: string
    default: ""
    description: "(Optional) Provide the local address of VSM iso package"


