#!/bin/bash
# This hook is run directly after install

source ./hooks/lib/common.sh

juju-log "start: handling hook"

create_vsm_vm 
if [ $? -eq 1 ]; then
    exit 1
fi 

start_vsm_vm 
if [ $?  -eq 1 ]; then
    exit 1
fi

juju-log "start: successfully running!"
